[package]
name = "kaku"
version = "0.1.0"
description = "A calm writing editor for long-form articles"
authors = ["k0suk"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
